### ISSUE TITLE
xinkule。 左右滑动到及限时，滑动手柄显示不完整。你应该根据手柄大小增加左右padding

### ISSUE THREAD

**Issue by bakboem** [zhoushuangjian001/flutter_idkit#1]

**Comment by zhoushuangjian001** [comment]
好的，谢谢支持

**Comment by zhoushuangjian001** [comment]
@bakboem   您好，你看到的在极限时，因为滑动块是在放大，导致超出。当您手指松开时，滑动块缩小就不会超出视图。如果你想控制可以设置  trackIndent 参数，该参数是控制滑动的缩进，也就是你说的  padding 。

**Comment by bakboem** [comment]
可能是需求不太一样，我需要足够大的滑动块。我已经通过flutter 原生双向滑动组件解决了这个问题。感觉设置滑动条最大长度时应该考虑(减去)滑动块最大宽度。
