### ISSUE TITLE
可以直接获取图像真实内容的大小realContentImage，右边和下边会少1~2个像素点，不知道可以优化一下吗？

### ISSUE THREAD

**Issue by ShuangZiMoYin** [zhoushuangjian001/flutter_idkit#2]
![image](https://github.com/zhoushuangjian001/flutter_idkit/assets/21330986/4ef462e4-aee2-4043-b909-ad627b2ff842)
![image](https://github.com/zhoushuangjian001/flutter_idkit/assets/21330986/de2f6f6e-83aa-49ea-ae0a-cbb51d958899)

**Comment by zhoushuangjian001** [comment]
@ShuangZiMoYin  由于原始图像，底部虚化。在计算颜色容差时被是被为白色。你可以降低  `tolerance` 的值，提高颜色容差计算精度。
![image](https://github.com/zhoushuangjian001/flutter_idkit/assets/13476336/a57e219f-098a-4517-819b-31a30b6a9f4b)
